SELECT PA.*,
         P.CODPROD,
         P.DESCRPROD,
         P2.CODPROD,
         P2.DESCRPROD,
         P.AD_CODMODELO,
         P2.AD_CODMODELO
    FROM TPRLPA PA, TGFPRO P, TGFPRO P2
   WHERE     (P.AD_CODMODELO IN ('CO55', 'CA45', 'GM60', 'CO55'))
         AND IDPROC = 26
         AND P.CODPROD = PA.CODPRODPA
         AND P2.CODPROD NOT IN (SELECT DISTINCT (CODPRODPA) FROM TPRLPA)
         AND (P.AD_CODCOR = P2.AD_CODCOR OR P.AD_CODCOR = DECODE (P2.AD_CODCOR, 7, 7, 2, 2, 3, 2)) AND
               (P.AD_COR = P2.AD_COR OR DECODE (P2.AD_COR,  'JATEADO   ', 'JATEADO   ', 'OURO ENV. ', 'BEGE      ', 'MARMACQUA ', 'AZUL      ', 'PRETO     ', 'PRETO     '  ) = P.AD_COR) AND
             P.CODPROD <> P2.CODPROD
         AND (P.AD_CODMODELO = P2.AD_CODMODELO OR DECODE (P2.AD_CODMODELO,  'CO55', 'CO55', 'CA45', 'CA45', 'GM60', 'GM60', 'CO55') = P.AD_CODMODELO) AND
             (P2.AD_SUPORTE = P.AD_SUPORTE
              OR (DECODE (P2.AD_SUPORTE, 'N', 'N', 'APX37', 'AP37' ) = P.AD_SUPORTE))
         AND P2.AD_CODMODELO IN ( 'CO55', 'CA45', 'GM60', 'CO55' )
ORDER BY P2.CODPROD ASC